# Generated by Django 4.2.19 on 2025-03-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanager6000', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='owner',
            field=models.CharField(default='', max_length=255),
        ),
    ]
