# Generated by Django 5.1.6 on 2025-03-17 06:24

import hotelmanager6000.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotelmanager6000", "0003_alter_hotel_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=hotelmanager6000.models.hotel_image_path,
            ),
        ),
    ]
