# Generated by Django 5.2 on 2025-04-13 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='collectionauthorizeduser',
            table='collection_authorized_users',
        ),
    ]
