# Generated by Django 5.2 on 2025-04-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_alter_collectionauthorizeduser_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_region',
            field=models.BooleanField(default=False),
        ),
    ]
