# Generated by Django 5.1.6 on 2025-03-20 20:30

import patron.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0002_collection_collectionaccessrequest_item_borrowing'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=patron.models.hotel_image_path),
        ),
    ]
