# Generated by Django 5.1.6 on 2025-03-26 00:50

import django.db.models.deletion
import patron.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0004_hotel_created_by_alter_hotel_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=patron.models.room_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='patron.hotel')),
            ],
            options={
                'unique_together': {('hotel', 'number')},
            },
        ),
        migrations.AddField(
            model_name='item',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_items', to='patron.room'),
        ),
        migrations.CreateModel(
            name='CollectionRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='patron.collection')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_collections', to='patron.room')),
            ],
            options={
                'unique_together': {('collection', 'room')},
            },
        ),
    ]
