# Generated by Django 5.1.6 on 2025-03-26 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0005_room_item_room_collectionroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_collections', to='patron.hotelbooking')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='patron.collection')),
            ],
            options={
                'unique_together': {('collection', 'booking')},
            },
        ),
    ]
