# Generated by Django 5.1.6 on 2025-03-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0006_collectionbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WISHLIST', 'Wishlist')], default='PENDING', max_length=10),
        ),
    ]
