# Generated by Django 5.1.6 on 2025-03-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0008_alter_hotelbooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
