# Generated by Django 5.1.6 on 2025-03-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0009_alter_hotel_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='location',
        ),
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(default='Charlottesville', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.CharField(default='United States', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='state',
            field=models.CharField(default='Virginia', max_length=100),
            preserve_default=False,
        ),
    ]
