# Generated by Django 5.1.6 on 2025-03-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0010_remove_hotel_location_hotel_city_hotel_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='street_address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
