# Generated by Django 5.1.6 on 2025-04-08 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0011_hotel_street_address'),
        ('patron', '0012_review_created_at'),
    ]

    operations = [
    ]
