# Generated by Django 5.1.6 on 2025-03-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0012_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='num_people',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=5),
            preserve_default=False,
        ),
    ]
