# Generated by Django 5.1.6 on 2025-04-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0013_merge_20250408_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='name',
        ),
        migrations.AddField(
            model_name='hotel',
            name='room',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
