# Generated by Django 5.1.6 on 2025-03-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0013_hotel_num_people_hotel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
