# Generated by Django 5.1.6 on 2025-04-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0014_remove_hotel_name_hotel_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='state',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='street_address',
        ),
        migrations.AddField(
            model_name='hotel',
            name='floor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='max_num_of_occupants',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='num_of_bathrooms',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='num_of_beds',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='square_footage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
