# Generated by Django 5.1.6 on 2025-03-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0014_alter_hotel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='num_people',
            field=models.CharField(max_length=100),
        ),
    ]
