# Generated by Django 5.1.6 on 2025-04-04 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0011_hotel_street_address'),
        ('patron', '0015_alter_hotel_num_people'),
    ]

    operations = [
    ]
