# Generated by Django 5.1.6 on 2025-04-04 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0016_merge_20250404_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='num_people',
        ),
    ]
