# Generated by Django 5.1.6 on 2025-04-08 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0017_remove_hotel_num_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='name',
        ),
        migrations.AddField(
            model_name='hotel',
            name='room',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
