# Generated by Django 5.2 on 2025-04-14 08:30

import catalog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('catalog', '0001_initial'), ('catalog', '0002_alter_item_title'), ('catalog', '0003_item_hero_image_alter_item_representative_image'), ('catalog', '0004_remove_item_hero_image_item_hero_video_and_more'), ('catalog', '0005_remove_item_hero_video_item_hero_image'), ('catalog', '0006_item_price_per_night')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Available'), (1, 'Reserved'), (2, 'Maintenance')], default=0)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('representative_image', models.ImageField(blank=True, help_text='The thumbnail image for the item', null=True, upload_to=catalog.models.item_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_created', to=settings.AUTH_USER_MODEL)),
                ('hero_image', models.ImageField(blank=True, help_text='The main banner image for the item', null=True, upload_to=catalog.models.item_image_path)),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='ItemReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.item')),
            ],
            options={
                'db_table': 'item_review',
            },
        ),
    ]
