# Generated by Django 5.2 on 2025-04-14 04:49

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_item_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hero_image',
            field=models.ImageField(blank=True, help_text="A larger, more prominent image for the item's detail page", null=True, upload_to=catalog.models.item_image_path),
        ),
        migrations.AlterField(
            model_name='item',
            name='representative_image',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.item_image_path),
        ),
    ]
