# Generated by Django 5.2 on 2025-04-14 04:57

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_item_hero_image_alter_item_representative_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='hero_image',
        ),
        migrations.AddField(
            model_name='item',
            name='hero_video',
            field=models.FileField(blank=True, help_text="The main video for the item's detail page. Supported formats: MP4, WebM, OGG", null=True, upload_to=catalog.models.item_image_path),
        ),
        migrations.AlterField(
            model_name='item',
            name='representative_image',
            field=models.ImageField(blank=True, help_text='The thumbnail image for the item', null=True, upload_to=catalog.models.item_image_path),
        ),
    ]
