# Generated by Django 5.2 on 2025-04-14 05:04

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_item_hero_image_item_hero_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='hero_video',
        ),
        migrations.AddField(
            model_name='item',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='The main banner image for the item', null=True, upload_to=catalog.models.item_image_path),
        ),
    ]
