# Generated by Django 5.2 on 2025-04-27 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_squashed_0006_item_price_per_night'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='identifier',
        ),
    ]
