# Generated by Django 5.1.6 on 2025-03-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("google_login", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
