# Generated by Django 5.1.6 on 2025-03-17 06:04

import google_login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("google_login", "0002_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=google_login.models.user_profile_path
            ),
        ),
    ]
