name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: hootel_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run migrations
        env:
          SECRET_KEY: 'dummy_key_for_testing'
          DEBUG: 'False'
          DB_NAME: hootel_db
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_HOST: localhost
          DB_PORT: 5432
          AWS_STORAGE_BUCKET_NAME: dummy-bucket
          AWS_ACCESS_KEY_ID: dummy-key
          AWS_SECRET_ACCESS_KEY: dummy-secret
          AWS_S3_REGION_NAME: us-east-1
        run: python manage.py migrate --noinput

      - name: Run tests
        env:
          SECRET_KEY: 'dummy_key_for_testing'
          DEBUG: 'False'
          DB_NAME: hootel_db
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_HOST: localhost
          DB_PORT: 5432
          AWS_STORAGE_BUCKET_NAME: dummy-bucket
          AWS_ACCESS_KEY_ID: dummy-key
          AWS_SECRET_ACCESS_KEY: dummy-secret
          AWS_S3_REGION_NAME: us-east-1
        run: python manage.py test
